version: '3.8'

services:

  mysql:
    image: mysql:8.4
    container_name: pedido-mysql
    restart: always
    environment:
      MYSQL_DATABASE: db_pedido
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3310:3306"
    networks:
      - pedido-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s

  eurekaserver:
    build:
      context: ../eurekaserver
    image: eurekaserver:1.0
    container_name: pedido-eurekaserver
    ports:
      - "8761:8761"
    networks:
      - pedido-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      timeout: 10s
      retries: 5
      interval: 10s

  pedido:
    build:
      context: .
    image: pedido:1.0
    container_name: pedido-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8086:8086"
    networks:
      - pedido-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/actuator/health"]
      timeout: 10s
      retries: 5
      interval: 10s

networks:
  pedido-network:
    driver: bridge

