spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://mysql-notificacion:3306/db_notificacion}
    username: ${DB_USERNAME:dev}
    password: ${DB_PASSWORD:dev123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: false

app:
  pedido:
    url: ${PEDIDO_URL:http://pedido:8086}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eurekaserver:8761/eureka/}

logging:
  level:
    root: WARN
    org.springframework.web: WARN
    com.marketplace.notificacion: INFO