spring:
  application:
    name: usuario-service
  profiles:
    active: dev
    spring:
      application:
        name: usuario-service
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
      instance:
        prefer-ip-address: true