services:
  carrito:
    url: ${SERVICES_CARRITO_URL:http://carrito:8081}
  inventario:
    url: ${SERVICES_INVENTARIO_URL:http://inventario:8082}
  vendedor:
    url: ${SERVICES_VENDEDOR_URL:http://vendedor:8083}
  producto:
    url: ${SERVICES_PRODUCTO_URL:http://producto:8084}
  usuario:
    url: ${SERVICES_USUARIO_URL:http://usuario:8085}
  pedido:
    url: ${SERVICES_PEDIDO_URL:http://pedido:8086}
  pago:
    url: ${SERVICES_PAGO_URL:http://pago:8087}
  valoracion:
    url: ${SERVICES_VALORACION_URL:http://valoracion:8088}
  notificacion:
    url: ${SERVICES_NOTIFICACION_URL:http://notificacion:8089}
  reporte:
    url: ${SERVICES_REPORTE_URL:http://reporte:8090}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eurekaserver:8761/eureka/}

logging:
  level:
    root: WARN
    org.springframework.cloud.gateway: INFO
    com.marketplace.gateway: INFO