services:
  carrito:
    url: ${SERVICES_CARRITO_URL:http://localhost:8081}
  inventario:
    url: ${SERVICES_INVENTARIO_URL:http://localhost:8082}
  vendedor:
    url: ${SERVICES_VENDEDOR_URL:http://localhost:8083}
  producto:
    url: ${SERVICES_PRODUCTO_URL:http://localhost:8084}
  usuario:
    url: ${SERVICES_USUARIO_URL:http://localhost:8085}
  pedido:
    url: ${SERVICES_PEDIDO_URL:http://localhost:8086}
  pago:
    url: ${SERVICES_PAGO_URL:http://localhost:8087}
  valoracion:
    url: ${SERVICES_VALORACION_URL:http://localhost:8088}
  notificacion:
    url: ${SERVICES_NOTIFICACION_URL:http://localhost:8089}
  reporte:
    url: ${SERVICES_REPORTE_URL:http://localhost:8090}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.marketplace.gateway: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html