spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: usuario-service
          uri: lb://usuario
          predicates:
            - Path=/api/usuario/**

        - id: vendedor-service
          uri: lb://vendedor
          predicates:
            - Path=/api/vendedores/**

        - id: producto-service
          uri: lb://producto
          predicates:
            - Path=/api/producto/**

        - id: inventario-service
          uri: lb://inventario
          predicates:
            - Path=/api/inventarios/**

        - id: carrito-service
          uri: lb://carrito
          predicates:
            - Path=/api/carritos/**

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true