spring:
  application:
    name: pedido-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: false

server:
  port: ${SERVER_PORT:8086}

logging:
  level:
    root: ERROR
    org.springframework.web: WARN
    com.marketplace.pedido: INFO

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

app:
  producto:
    url: ${PRODUCTO_URL:http://localhost:8084}
