spring:
  application:
    name: pedido-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/db_pedido?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: false
    locations: classpath:db/migration

server:
  port: 8086

logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    com.marketplace.pedido: TRACE
  file:
    name: app.log
    path: ./logs

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

app:
  producto:
    url: ${PRODUCTO_URL:http://localhost:8084}