CREATE TABLE IF NOT EXISTS pago (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    metodo_pago VARCHAR(50) NOT NULL,
    comprobante VARCHAR(255) NOT NULL,
    fecha DATETIME NOT NULL,
    pedido_id BIGINT
    );