spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_reporte
    username: root
    password: Dev2026?
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: false

app:
  jwt:
    secret: dev-secret-key-dev-secret-key-dev-secret-key-123456
    expiration-ms: 86400000

logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    com.marketplace.reporte: TRACE
  file:
    name: app.log
    path: ./logs